package entity;
// Generated Oct 20, 2016 9:55:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Serializable code;
     private Serializable name;

    public Category() {
    }

	
    public Category(Serializable code) {
        this.code = code;
    }
    public Category(Serializable code, Serializable name) {
       this.code = code;
       this.name = name;
    }
   
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }




}


